#ifndef VIGIA_THEME_H
#define VIGIA_THEME_H




#define VIGIA_CELL_W 8
#define VIGIA_CELL_H 16
#define VIGIA_FONT_SIZE VIGIA_CELL_H


#define VIGIA_PAD_X 16
#define VIGIA_PAD_Y 8


#define VIGIA_SURFACE_HEIGHT(rows) (VIGIA_PAD_Y * 2 + (rows) * VIGIA_CELL_H)
#define VIGIA_CONTENT_CELLS(width) \
    (((width) - VIGIA_PAD_X * 2) / VIGIA_CELL_W)


#define VIGIA_SURFACE_RGBA    0x483939FFU
#define VIGIA_FOREGROUND_RGBA 0xEAE0CDFFU
#define VIGIA_DIM_RGBA        0xA29891FFU
#define VIGIA_WARNING_RGBA    0xC47B72FFU
#define VIGIA_KEYLINE_RGBA    0xEAE0CD8CU


#define VIGIA_MENU_TOP 12
#define VIGIA_MENU_HEIGHT 28
#define VIGIA_MENU_WIDTH_RATIO 0.5F
#define VIGIA_MENU_PADDING 12
#define VIGIA_MENU_TAG_WIDTH 24
#define VIGIA_MENU_REGION_GAP 12
#define VIGIA_MENU_SPINE_WIDTH 1
#define VIGIA_MENU_SPINE_HEIGHT 4
#define VIGIA_MENU_SPINE_ACTIVE_HEIGHT 8
#define VIGIA_MENU_TAG_SWAP_SECONDS 0.180F


#define VIGIA_TOAST_WIDTH 336
#define VIGIA_TOAST_CONTENT_CELLS VIGIA_CONTENT_CELLS(VIGIA_TOAST_WIDTH)
#define VIGIA_TOAST_MARGIN 16
#define VIGIA_TOAST_GAP 8
#define VIGIA_TOAST_BODY_MAX_LINES 2
#define VIGIA_TOAST_HEIGHT_PLAIN VIGIA_SURFACE_HEIGHT(2)
#define VIGIA_TOAST_HEIGHT_BODY1 VIGIA_SURFACE_HEIGHT(3)
#define VIGIA_TOAST_HEIGHT_BODY2 VIGIA_SURFACE_HEIGHT(4)
#define VIGIA_RECALL_ROW_HEIGHT VIGIA_SURFACE_HEIGHT(1)


#define VIGIA_OSD_WIDTH 220
#define VIGIA_OSD_HEIGHT VIGIA_MENU_HEIGHT


#define VIGIA_LAUNCHER_GAP 24
#define VIGIA_LAUNCHER_SHELF_DEPTH 16
#define VIGIA_LAUNCHER_SHELF_INSET 16
#define VIGIA_LAUNCHER_SHELF_LIP 4
#define VIGIA_LAUNCHER_SHELF_ALPHA 0.85F
#define VIGIA_LAUNCHER_LIP_TINT 0.30F
#define VIGIA_LAUNCHER_REFLECTION_ALPHA 0.20F
#define VIGIA_LAUNCHER_SINK 8
#define VIGIA_LAUNCHER_LIFT 4




#define VIGIA_ASCII_FIRST 32
#define VIGIA_ASCII_LAST 126
#define VIGIA_ASCII_COUNT (VIGIA_ASCII_LAST - VIGIA_ASCII_FIRST + 1)


#define VIGIA_TRACKING_LABEL VIGIA_CELL_W
#define VIGIA_TRACKING_CONTENT 0


#define VIGIA_MENU_OPEN_SECONDS 0.300F
#define VIGIA_MENU_CLOSE_SECONDS 0.180F
#define VIGIA_CONTENT_FADE_START 0.55F

typedef enum {
    VIGIA_TEXT_LABEL,
    VIGIA_TEXT_CONTENT,
    VIGIA_TEXT_MUTED,
    VIGIA_TEXT_REVERSE
} VigiaTextStyle;

#endif
